[pytest]
addopts = -v --html=reports/report.html --self-contained-html
testpaths = test tests_api

markers =
    ui: pruebas de interfaz de usuario (Selenium)
    api: pruebas de API/backend (Requests)
    smoke: pruebas críticas que deben pasar siempre
    regression: suite completa de regresión
    e2e: flujos end-to-end / ciclo de vida completo
